# Generated by Django 3.1 on 2025-01-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_ratingreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingreview',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
