# Generated by Django 3.1 on 2025-01-09 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20250109_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[['new', 'new'], ['Accepted', 'Accepted'], ['Completed', 'Completed'], ['Cancelled', 'Cancelled']], default='New', max_length=100),
        ),
    ]
