# Generated by Django 3.1 on 2025-01-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20250113_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[['Accepted', 'Accepted'], ['Dispatched', 'Dispatched'], ['Delivered', 'Delivered'], ['Cancelled', 'Cancelled']], default='Accepted', max_length=100),
        ),
    ]
